project:
  type: book
  preview:
      port: 4200
filters:
  - include-code-files
book:
  title: "Kriptoloji Giris"
  author: "Atilla Özgür"
  date: today
  date-format: "YYYY-MM-DD"
  cover-image: cover.png

  chapters:
    - index.qmd
    - intro.qmd
    - content/random-numbers.qmd
    - content/simetrik-sifreler.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



